# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.srcs/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib.xci
# IP: The module: 'fifo_w256_1024_r64_4096_ib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.srcs/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib.xci
# IP: The module: 'fifo_w256_1024_r64_4096_ib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexy/Documents/ISML_Research_Summer_2023/FIFO-Pipeline/FIFO-Pipeline.gen/sources_1/ip/fifo_w256_1024_r64_4096_ib/fifo_w256_1024_r64_4096_ib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w256_1024_r64_4096_ib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
